[build]
  publish = "html"

[[redirects]]
  from = "/css/*"
  to = "/../css/:splat"
  status = 200

[[redirects]]
  from = "/js/*"
  to = "/../js/:splat"
  status = 200

[[redirects]]
  from = "/assets/*"
  to = "/../assets/:splat"
  status = 200

[[redirects]]
  from = "/mock-data/*"
  to = "/../mock-data/:splat"
  status = 200 
